### ISSUE TITLE
[TeX input] processing within \text{}

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#135]
From a quick test, it seems that v3 keeps v2's behavior and only allows `$`, `\ref`, `\eqref` within text mode (`\text`, `\mbox` etc).

It would be very helpful to revisit this and make it to some degree configurable.

My particular use case is linking. I need a custom macro for linking that goes beyond what `ref` and `eqref` can provide; and I need to support this macro in both modes.

**Comment by pkra** [comment]
I could actually create HTML markup instead. Are there any improvements for mixed content?

**Comment by pkra** [comment]
Something else reproduced from v2 is that `\` and `\\` both yield a backspace. That seems inconsistent.

**Comment by dpvc** [comment]
> Are there any improvements for mixed content?

We have kept it in mind during the development of the internal structure, but have not implemented anything for it yet.

> `\` and `\\` both yield a backspace 

I assume you mean backslash?  Yes, they do.  Do you think that `\` should simply be removed?

**Comment by dpvc** [comment]
> It would be very helpful to revisit this and make it to some degree configurable.

Do you have a suggestion of what that would consist of?  In v2, one was able to override the `InternalText()` method in order to do additional processing.  In v3, it would still be possible to do something similar, though I haven't looked at Volker's implementation for that specifically.  What kind of configuration do you have in mind?

**Comment by pkra** [comment]
> We have kept it in mind during the development of the internal structure, but have not implemented anything for it yet.

Thanks. That might be useful to talk to the TC about.

> I assume you mean backslash? 

Oops, yes. Sorry.

> Do you think that `\ `should simply be removed?

That seems reasonable to me but I don't have an opinione (beyond clarifying it).

> What kind of configuration do you have in mind?

I'd be happy to work towards a situation where MathJax v3 by default parses for macros inside of `\text{}` (et al) but I'd understand if that's too radical. Maybe a Boolean to enable/disable parsing inside `\text{}` would be a start; then the responsibility falls on the author to ensure that the macros they use inside `\text{}` creates a suitable internal structure. 

But I'm aware that this is complicated and that I'm not thinking about this in full depth.

**Comment by dpvc** [comment]
I have put together an [extension for v2](https://github.com/dpvc/MathJax/blob/text-macros/unpacked/extensions/TeX/text-macros.js) that allows the processing to (some) text-mode macros.  Volker hasn't seen it yet, and I don't know how well it will fit in with the v3 architecture, but I'm sure something like it could be done.  Perhaps that is a sufficient solution?

**Comment by dpvc** [comment]
The text-macros extension is in v3.1 released today.
