### ISSUE TITLE
Wrong TexClass

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-src#147]
https://github.com/mathjax/mathjax-v3/blob/cd0e103318a08788309da1b4e39cb70458e975ac/mathjax3-ts/input/tex/braket/BraketItems.ts#L82

The closeNode needs `texclass` close.

**Comment by dpvc** [comment]
@zorkow, I'm not sure I understand what this means.  Can you fix this if you want the bracket notation to be part of the production release?

**Comment by dpvc** [comment]
I believe this has been fixed with PR 271.
