### ISSUE TITLE
natural reflow for inline content 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#173]
As discussed in the past, it would be good if v3 could allow inline content to reflow naturally (ie. without re-rendering).

For CSS, something like https://github.com/KaTeX/KaTeX/pull/1287 might be a helpful inspiration.

For SVG, this would require moving towards multiple SVG fragments (which would be a very good move but perhaps worth a separate, larger discussion).

**Comment by bfirsh** [comment]
Ooh -- has this been added in v3? Or is this close a "wontfix"? :)

**Comment by dpvc** [comment]
@bfirsh, no, it is not implemented.  Peter has been closing all his issues.  I'm not sure why he closed some of them.  This is still a good feature request.  But it should be in the mathjax/MathJax repository (along with most of the other feature requests).
