### ISSUE TITLE
relicensing

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#176]
v3 seems to offer the opportunity to re-license the code as no third party contributors have added to the code base.

Would you consider a change to a more permissive license (e.g., MIT)?

**Comment by dpvc** [comment]
IANAL, so I'm not sure entirely what the differences between the licenses are.  What I see off hand is that Apache2 has patent protection, and requires changes to be clearly marked in the source code, while MIT doesn't.

Can you explain the need for the change, and what would be gained?

**Comment by pkra** [comment]
> Can you explain the need for the change, and what would be gained?

The main gain would be compatibility to GPL2 licenses. This came up regularly when GPL2 projects think about including MathJax (some editors, some CMSs) -- because of incompatibility of the licenses, they cannot ship MathJax. This will be even more of a problem with modern bundling approaches.
