### ISSUE TITLE
TeX input, amsmath: change `\sideset` implementation to generate multiscripts

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#177]
Cf. https://github.com/mathjax/MathJax/issues/1217.

AFAICT,  the current beta.3 still creates subsups.

Is this planned?

**Comment by dpvc** [comment]
So far, the TeX jax produces (essentially) the same results as the v2 TeX input jax.  We have not adjusted individual macros at this point, except where necessary for changes in the infrastructure.  Improvements to the TeX output will come in a future release.

**Comment by pkra** [comment]
Thanks, I understand that. Could you tell me if you are planning to include such a change in v3?

**Comment by dpvc** [comment]
I would like it to use `mmultiscripts`, but (as pointed out in the discussion of #1217), it may not be a trivial change.

**Comment by pkra** [comment]
Thanks.
