### ISSUE TITLE
[TeX/amsmath] xalignat, xxalignat, and flalign support 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#212]
Will these environments (and their starred versions) be added to the amsmath extension in v3? 

Cf. @dpvc's example at https://groups.google.com/forum/#!topic/mathjax-users/8YxzxF-m_hM.

**Comment by dpvc** [comment]
They are not currently in the ams extension, and we are in the process of finalizing the v3 release.  But they can probably be added.
