### ISSUE TITLE
"Double exponent: use braces to clarify" erroneous error?

### ISSUE THREAD

**Issue by dstarbuc** [mathjax/MathJax-src#314]
I'm getting "Double exponent: use braces to clarify" in MJ3 for the following code that worked in MJ2.7.4. possible bug?
$ \boldsymbol {c'}^{(t)} = \boldsymbol {c}^{(t)} $
![error_exponent](https://user-images.githubusercontent.com/10466756/62059498-6ae2e480-b1f1-11e9-868c-440d9a68ff54.jpeg)

**Comment by dstarbuc** [comment]
as you can see from the screenshot, similar coding worked in the line above.

**Comment by dpvc** [comment]
Yes, looks like a bug.  We'll look into it.

**Comment by dpvc** [comment]
OK, I have found the issue and have made a pull request with the fix.  Thanks for the bug report!
