### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by streamich** [mathjax/MathJax-src#341]
How can I use this library with classic Webpack bundler? I've scanned through a lot of documentation on the site and code in this repo, I still don't understand how to use this library.

I would like to do something like this:

```js
import MathJax from 'mathjax';

let html = MathJax.tex2chtml('\\sqrt{x^2+1}', {em: 12, ex: 6, display: false});
```

**Comment by invaliduser** [comment]
Embarrassed to say the same.

**Comment by pkra** [comment]
The nodejs demos are probably helpful, e.g., https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2chtml (without the yargs CLI option handling).

**Comment by dpvc** [comment]
The [README](https://github.com/mathjax/MathJax-src#using-mathjax-components-in-node-applications) for this site also include an example of how to use MathJax from node in something like the way you are suggesting.  Using your example from above, 

```
import mathjax from "mathjax";

mathjax.init({
  loader: {
    require: require,
    paths: {mathjax: 'mathjax/es5'},
    load: ['input/tex', 'output/chtml']
  }
}).then((MathJax) => {
  const svg = MathJax.tex2chtml('\\sqrt{x^2+1}', {em: 12, ex: 6, display: false});
  let html = MathJax.startup.adaptor.outerHTML(svg);
  // your other code here
}).catch((err) => console.log(err.message));
```

This approach is promise-based, so you will need to use those.  If you want to operate synchronously, you can look at the examples in the [preload](https://github.com/mathjax/MathJax-demos-node/tree/master/preload#preloaded-component-examples) directory of the [MathJax Node Demos](https://github.com/mathjax/MathJax-demos-node#MathJax-demos-node) repository for example of how to do this with MathJax Components, or in the [direct](https://github.com/mathjax/MathJax-demos-node/tree/master/direct#non-component-based-examples) directory, as Peter suggests, for how to access the MathJax modules directly from node.
