### ISSUE TITLE
\longrightarrow and \rightarrow ar of same length

### ISSUE THREAD

**Issue by anuragnagardeveloper** [mathjax/MathJax-src#363]
why  \longrightarrow and \rightarrow are of similar length

**Comment by dpvc** [comment]
They aren't for me.  Here are what I get for the two:

<img width="64" alt="arrows" src="https://user-images.githubusercontent.com/432782/66337828-e6f25a80-e90d-11e9-9fe7-c301963e259c.png">

If you can provide the expression where you are seeing the same length, we can look into it.  It might help to say what browser and OS versions you are using.

**Comment by anuragnagardeveloper** [comment]
It worked thanks
