### ISSUE TITLE
AsciiMath with \$ delimiters

### ISSUE THREAD

**Issue by Mogztter** [mathjax/MathJax-src#364]
When using `\$` as a delimiter, AsciiMath is not working as excepted.
You can reproduce this issue using the following HTML page:

```html
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AsciiMath</title>
</head>
<body>
<h1>AsciiMath</h1>
<section>
<p>Lorem ipsum \$((a),(b))\$ dolor</p>
</section>
<section>
<p>adipiscing elit \${(2x,+,17y,=,23),(x,-,y,=,5):}\$ sed</p>
</section>
<script>
MathJax = {
  loader: {load: ['input/asciimath', 'output/chtml', 'ui/menu']},
  asciimath: {
    delimiters: [['\\$','\\$']]
  }
}
</script>
<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
</body>
</html>
```

And here's the result on Chrome and Firefox:

![result](https://user-images.githubusercontent.com/333276/66383679-bb2ead80-e9bd-11e9-971c-f8e847a32d54.png)

As you can see the formulas are rendered but the text `{(2x,+,17y,=,23),(x,-,y,=,5):}` is still present.

And with the following HTML page the formulas are not rendered at all:

```html
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AsciiMath</title>
</head>
<body>
<h1>AsciiMath</h1>
<section>
<p>\$((a),(b))\$</p>
</section>
<section>
<p>\${(2x,+,17y,=,23),(x,-,y,=,5):}\$</p>
</section>
<script>
MathJax = {
  loader: {load: ['input/asciimath', 'output/chtml', 'ui/menu']},
  asciimath: {
    delimiters: [['\\$','\\$']]
  }
}
</script>
<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
</body>
</html>
```

![error](https://user-images.githubusercontent.com/333276/66384088-62abe000-e9be-11e9-812b-0b7f875d1008.png)

It seems related to the delimiter `\$`.
I cannot reproduce this issue when using `$$` as delimiter:

```html
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AsciiMath</title>
</head>
<body>
<h1>AsciiMath</h1>
<section>
<p>$$((a),(b))$$</p>
</section>
<section>
<p>$${(2x,+,17y,=,23),(x,-,y,=,5):}$$</p>
</section>
<script>
MathJax = {
  loader: {load: ['input/asciimath', 'output/chtml', 'ui/menu']},
  asciimath: {
    delimiters: [['$$','$$']]
  }
}
</script>
<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
</body>
</html>
```

Please note that it was working with MathJax 2.7.6.

**Comment by dpvc** [comment]
Since you are loading `tex-html.js`, you are getting both the AsciiMath and TeX input jax, and so both are running on the page.  It looks like the TeX input is interfering with the AsciMath.  Switch to loading `startup.js` instead and it should work.

**Comment by Mogztter** [comment]
Thanks for your quick reply.

> Since you are loading tex-html.js, you are getting both the AsciiMath and TeX input jax, and so both are running on the page. It looks like the TeX input is interfering with the AsciMath.

I do want to be able to use both (but obviously not at the same time).

> Switch to loading startup.js instead and it should work.

Using the following configuration with `startup.js` does not work either:

```js
MathJax = {
  tex: {
    inlineMath: [['\\(', '\\)']],
    displayMath: [['\\[', '\\]']],
    tags: 'none'
  },
  options: {
    ignoreHtmlClass: 'nostem|noasciimath'
  },
  asciimath: {
    delimiters: [['\\$', '\\$']]
  },
  loader: {load: ['input/asciimath', 'input/tex-base', 'output/chtml', 'ui/menu', '[tex]/require']}
}
```

In this case, TeX should not conflict since I'm not using the same delimiters... ?

**Comment by dpvc** [comment]
Try adding

    processEscapes: false

to the `tex` block of your configuration.  The TeX input jax usually converts `\$` to a plain `$`, and that means both jax are trying to handle the `\$` and things get messed up by that.

Since you want both TeX and AsciiMath, you can go back to using `tex-chtml.js` if you set `processEscapes: false`, which will require fewer network transfers.   So the new setup would be

```
<script>
MathJax = {
  tex: {
    inlineMath: [['\\(', '\\)']],
    displayMath: [['\\[', '\\]']],
    processEscapes: false,
    tags: 'none'
  },
  options: {
    ignoreHtmlClass: 'nostem|noasciimath'
  },
  asciimath: {
    delimiters: [['\\$', '\\$']]
  },
  loader: {load: ['input/asciimath']}
}</script>
<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
```

**Comment by Mogztter** [comment]
Thanks I will give it a try and report back 😁

**Comment by Mogztter** [comment]
It's working! Thanks @dpvc for your help.
Do you think we should add a note in the documentation because I'm pretty sure `processEscapes` was `false` by default in MathJax 2.x?

**Comment by libinglong** [comment]
> It's working! Thanks @dpvc for your help. Do you think we should add a note in the documentation because I'm pretty sure `processEscapes` was `false` by default in MathJax 2.x?

I have upgraded mathjax from 2 to 3. This problem makes me suffering a lot.
