### ISSUE TITLE
A11y problem on edge (Windows 10)

### ISSUE THREAD

**Issue by akashdeepbansal** [mathjax/MathJax-src#368]
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.0/extensions/a11y/wgxpath.install.js

**Comment by zorkow** [comment]
wicked good xpath was necessary to use full xpath expression is in Edge, which is needed for SRE. With Edge moving to blink, this might no longer be necessary. 
Either way, it should load it from the correct URL.
