### ISSUE TITLE
`laodDefaultMathJax` is not defined

### ISSUE THREAD

**Issue by Ebanflo42** [mathjax/MathJax-src#375]
There appears to be a typo at https://cdn.rawgit.com/mathjax/MathJax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML at line 19. The script calls `laodDefaultMathJax` instead of `loadDefaultMathJax`.

**Comment by dpvc** [comment]
This was fixed in the 2.7.2 release in 2017.  Since we can't change the files in an existing release, the only solution is to change the URLs to refer to a later release.  The current release is 2.7.6, so it would be best to change your 2.7.1 references to 2.7.6.
