### ISSUE TITLE
[SVG]Not working `\varDelta` 

### ISSUE THREAD

**Issue by YiNiCoo** [mathjax/MathJax-src#376]
The render result of the command `\varDelta` is blank.
An empty g element：<g data-mml-node="mi"></g>
component：tex-svg.js

**Comment by dpvc** [comment]
Thanks, I can verify the bug, and will look into it.

**Comment by dpvc** [comment]
It turns out that the data for the character is missing from the font file.  The data files were generated by scripts from the v2 data, and since the organization of the font data is quite different in v3, the scripts are pretty complicated.  Apparently this character was not handled properly and the data didn't make it into the v3 file.

I have made a PR that updates the file to include the missing data.

You can use

```
<script>
MathJax = {
  startup: {
    ready() {
      var italic = MathJax._.output.svg.fonts.tex.italic.italic;
      var AddPaths = MathJax._.output.svg.FontData.AddPaths;
      AddPaths(italic, {
        0x394: '574 715L582 716Q589 716 595 716Q612 716 616 714Q621 712 621 709Q622 707 705 359T788 8Q786 5 785 3L781 0H416Q52 0 50 2T48 6Q48 9 305 358T567 711Q572 712 574 715ZM599 346L538 602L442 474Q347 345 252 217T157 87T409 86T661 88L654 120Q646 151 629 220T599 346'
      }, {});
      MathJax.startup.defaultReady();
    }
  }
}
</script>
```

just *before* loading MathJax in order to patch the data yourself, if you want to get the fix before the next release.

**Comment by YiNiCoo** [comment]
Is the command `\div` the same reason?

**Comment by YiNiCoo** [comment]
> It turns out that the data for the character is missing from the font file. The data files were generated by scripts from the v2 data, and since the organization of the font data is quite different in v3, the scripts are pretty complicated. Apparently this character was not handled properly and the data didn't make it into the v3 file.
> 
> I have made a PR that updates the file to include the missing data.
> 
> You can use
> 
> ```
> <script>
> MathJax = {
>   startup: {
>     ready() {
>       var italic = MathJax._.output.svg.fonts.tex.italic.italic;
>       var AddPaths = MathJax._.output.svg.FontData.AddPaths;
>       AddPaths(italic, {
>         0x394: '574 715L582 716Q589 716 595 716Q612 716 616 714Q621 712 621 709Q622 707 705 359T788 8Q786 5 785 3L781 0H416Q52 0 50 2T48 6Q48 9 305 358T567 711Q572 712 574 715ZM599 346L538 602L442 474Q347 345 252 217T157 87T409 86T661 88L654 120Q646 151 629 220T599 346'
>       }, {});
>       MathJax.startup.defaultReady();
>     }
>   }
> }
> </script>
> ```
> 
> just _before_ loading MathJax in order to patch the data yourself, if you want to get the fix before the next release.

Thanks for the solution. 
Is `\div` the same reason?

**Comment by dpvc** [comment]
> Thanks for the solution.
> Is \div the same reason?
> 

The \div macro works for me in SVG, so I would say "no".  Can you provide more information about what is happening?

Davide

**Comment by YiNiCoo** [comment]
> Thanks for the solution. Is \div the same reason?
> The \div macro works for me in SVG, so I would say "no". Can you provide more information about what is happening?

With the following Initialize config，it will render like '∇⋅'
MathJax = {
      loader: {
        load: ['[tex]/physics']
      },
      tex: {
        packages: {
          '[+]': ['physics']
        }
      }
    }

**Comment by dpvc** [comment]
Yes, that is correct.  The physics package redefines `\div` to be the divergence operator (as in "div", "grad", and "curl").  The original `\div` from the AMS package is renamed to `\divisionsymbol` if you need it when using the physics package.

**Comment by YiNiCoo** [comment]
> Yes, that is correct. The physics package redefines `\div` to be the divergence operator (as in "div", "grad", and "curl"). The original `\div` from the AMS package is renamed to `\divisionsymbol` if you need it when using the physics package.

Thanks for your patience. I see

**Comment by qq240814476** [comment]
mark
