### ISSUE TITLE
Add current version to the README.md and the website?

### ISSUE THREAD

**Issue by Pomax** [mathjax/MathJax-src#380]
It would be super useful to see what the current version of MathJax is both on the site and near the top of the README.md, so that people can easily tell whether the version they're using is still current (or current enough), or old enough to require updating.

**Comment by dpvc** [comment]
Good point.  I will add that on the next update.

**Comment by Pomax** [comment]
Where can one find this information? I had a look at the README front pages but don't see a true version mentioned anywhere?

**Comment by dpvc** [comment]
Its right [there](https://github.com/mathjax/MathJax-src#mathjax-source-repository)

<img width="1039" alt="versions" src="https://user-images.githubusercontent.com/432782/74356229-ff76f380-4d8b-11ea-9918-5c741a880fe3.png">

**Comment by dpvc** [comment]
It is in both the source and main MathJax repositories.

**Comment by Pomax** [comment]
ahhhh subtle. But, absolutely, it's right there. Thanks so much!

**Comment by dpvc** [comment]
Sorry if that is not what you meant.  These "shields" seem to be a very common way of doing this on many GitHub sites.  They are generated automatically (using an image tag to a site called shields.io) so that they will always be current.

**Comment by Pomax** [comment]
they are, it's just a color contrast I can't easily see.

**Comment by dpvc** [comment]
I can see about changing the color.
