### ISSUE TITLE
The rendering results of `\sin x^2` and `\sin {x}^{2}` should be the same, but not

### ISSUE THREAD

**Issue by YiNiCoo** [mathjax/MathJax-src#382]
The rendering results of `\sin x^2` and `\sin {x}^{2}` should be the same, but not. One space is missing.

**Comment by dpvc** [comment]
This is a duplicate of mathjax/MathJax#2187, and is fixed in PR #344 

On a side note, please report bugs in the mathjax/MathJax issue tracker (so all the bugs ore in one place) rather than on the MathJax-src issue tracker.  Thanks!

**Comment by YiNiCoo** [comment]
OK
