### ISSUE TITLE
MathJax fails in IE mode in Edge

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-src#386]
Fails to load when using IE mode in Edge.

**Comment by dpvc** [comment]
I'm not able to reproduce this.  Can you give an example?

**Comment by zorkow** [comment]
That has changed: When I run IE mode in Edge (via console emulation), I MathJax works, after a long load time.
However, when running it in IE 11 itself, it fails with a `Symbol undefined` error.

**Comment by dpvc** [comment]
Can you check that the page actually is in E11 mode, not one of the earlier version's emulation?  The page may need to have 

```
<meta http-equiv="x-ua-compatible" content="ie=edge">
```

in the head or it may end up in IE7 mode. Also, be sure you have the 

```
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
```

script loaded before the MathJax script, as that is definitely needed for IE11.

**Comment by zorkow** [comment]
This is our own mathjax.org page. And it has all these settings, but maybe the polyfill is not loaded correctly? Do the samples work for you on IE11?

**Comment by dpvc** [comment]
It looks like mathjax.org is not loading the polyfill.  I'll have to add that and see if that fixes it.

Try one of the [web demos](https://mathjax.github.io/MathJax-demos-web/tex-chtml.html) and see if that works for you.  It does for me.

**Comment by zorkow** [comment]
The webdemo site itself does not work. It's missing the `meta` tag.
I got it to work on a separate page. However, a11y fails, as somehow the `mathml` element is corrupted.

**Comment by dpvc** [comment]
> The webdemo site itself does not work. It's missing the `meta` tag.

I know, I was in the process of fixing them.  but you can use the emulation tab in the console window to change to IE11 explicitly.

> a11y fails, as somehow the mathml element is corrupted.

Can you give me any more information on that?  Are you using the development branch, or the v3.0.0?

**Comment by dpvc** [comment]
I added the polyfill to the mathjax.org site, and now MathJax runs, but the output isn't good.  I think some CSS is affecting the results, because the same equations render properly in the demos.

**Comment by zorkow** [comment]
Yes, I am using `develop` with `es5/tex-chtml.js`. Configurations are the usual.

**Comment by zorkow** [comment]
> I added the polyfill to the mathjax.org site, and now MathJax runs, but the output isn't good. I think some CSS is affecting the results, because the same equations render properly in the demos.

I see what you mean. The roots and divisions are all off. I get the same mathml error on the page when switching on a11y.

**Comment by zorkow** [comment]
It could be a problem in sre that something goes wrong with the creation the xml parsing of the enriched  structure. I am investigating.

**Comment by dpvc** [comment]
Yes, the message does indicate that the parsing is not producing a `<math>` node, but a `#text` node.  I haven't tracked it down further, as it is very painful for me to work with IE, and I've currently run out of time.

I did fix the website, however, so the math displays properly in IE.  It was some CSS that styles `* + *` (not something I set up), and my original fix to disable that in MathJax output used `unset`, which IE doesn't support.  Sigh.

**Comment by zorkow** [comment]
For some reason in IE the nodes I produce do not have an `outerHTML`. I am using the browsers `DOMParser`, so I am not sure what goes wrong. Seems to be an IE problem. In 2.7 this did not show up as sre would return a string. 
The `toString` method in `semantic-enrich.ts` produces an `[Object object]` and hence does not work either.

**Comment by dpvc** [comment]
Before recently (I don't remember exactly when), MathML elements did not have `outerHTML` properties.  That may still be true in IE11 because of its age.  In v2, we generally put the `math` node into an HTML `div` and took the `innerHTML` of the `div`.  Perhaps that would work.

Alternatively, if you are using the DOM adaptor to get the `outerHTML`, we could modify the HTMLadaptor to use `outerHTML` if the node has it, and use the `div` trick otherwise.
