### ISSUE TITLE
`postcompile` script not running

### ISSUE THREAD

**Issue by ShaMan123** [mathjax/MathJax-src#402]
`npm run compile` doesn't run `npm run postcompile` because the process exits due to `typescript` compilation errors causing an error when trying to use `mhchem` file.

**Comment by dpvc** [comment]
It works for me.  Can you describe your environment a bit more?  Did you obtain MathJax via GitHub or npm, for example?  What OS are you working on?  What typescript errors are you getting?  What version of typescript has been installed?

**Comment by ShaMan123** [comment]
installed via `yarn`, working on windows
```
typescript@3.7.2

```

I think it's to do with `tsconfig`. I'm getting the compilation output that contains `ts` errors. Of course non of this is critical but it terminates the process, thus not completing `compile` script.

**Comment by dpvc** [comment]
OK, thanks.  MathJax was compiled using Typescript 3.5.2, so you might try `npm install Typescript@3.5.2` and see if that allows it to compile without error.  We should probably use `~3.5.2` or `@3.5.2` rather than `^3.5.2` in `package.json`.
