### ISSUE TITLE
Include definitions (.d.ts) files in npm

### ISSUE THREAD

**Issue by artagnon** [mathjax/MathJax-src#620]
This would allow auto-complete in vscode, and ease development greatly!

**Comment by dpvc** [comment]
The `.d.ts` files are in the `js` directory along with the compiled `.js` files.  They are available in the `mathjax-full` npm package if you are working through npm.

**Comment by artagnon** [comment]
Yes, I noticed. My auto-complete on vscode is very sub-optimal, and I don't know why. Possibly a limitation of vscode? Is it worth discussing?

**Comment by dpvc** [comment]
We do not use vscode ourselves, so you won't be able to get much advice here.  Perhaps the [MathJax Developer Forum](https://groups.google.com/g/mathjax-dev) or the [MathJax User's Forum](https://groups.google.com/g/mathjax-users) might be a place where you can get some information on that?

**Comment by artagnon** [comment]
Okay, thanks.
