### ISSUE TITLE
tex2svg  when meet 𝝅 is transform fail  see the details on the IMG

### ISSUE THREAD

**Issue by OnePsycho** [mathjax/MathJax-src#643]
![59941abb9433849b7ef4f8f4258b6ce](https://user-images.githubusercontent.com/43296632/111755398-05ff6500-88d4-11eb-836c-f166f682b89c.png)

**Comment by dpvc** [comment]
I'm transferring this to the MathJax issue tracker, where the issue template indicates it should have been filed.
