### ISSUE TITLE
[physics] Bugs in Physics package

### ISSUE THREAD

**Issue by ickc** [mathjax/MathJax-src#694]
First, thanks @zorkow for writing the current Physics package implementation in MathJax 3.

I'm trying to file bug report in the current implementation that differs with the LaTeX physics package based on my test.

The following commands are not working:

```latex
\Bqty{ \frac{1}{1+\frac{1}{2}} }
\qsince
```

**Comment by zorkow** [comment]
Well, I am very glad that the package is useful. 
There are a couple of issues that have been identified in the physics package. See also [issue 2449 on the MathJax tracker](https://github.com/mathjax/MathJax/issues/2449).  For 3.2 we will add a few more LaTeX packages as well as go over some of the existing ones. So let me know if there's anything else that's missing.

**Comment by ickc** [comment]
Thanks!
