### ISSUE TITLE
Hardcoded font paths not recognized by webpack

### ISSUE THREAD

**Issue by jasongrout** [mathjax/MathJax-src#70]
In https://github.com/jupyterlab/jupyter-renderers/pull/69, we made a JupyterLab plugin to use mathjax 3 to render mathematics throughout the system. The rendering layout seems to work okay, except that it is trying to get a bunch of font files which it can't find.

It seems that the font paths are hardcoded at, for example, https://github.com/mathjax/mathjax-v3/blob/master/mathjax3-ts/output/chtml/fonts/tex.ts#L253

JupyterLab uses webpack to bundle all of its js up, and normally if a font file is referenced in a static css file, webpack can find that font file, copy it to the output directory, and change the font reference in the css to point to the right font file location. With Mathjax 3, it seems that webpack doesn't recognize these URLs (things are too dynamic), so it doesn't know to package up the font files and can't change the references to point to the correct location.

I'm not sure a way around this. @zorkow and I just talked about it, and I got the impression that the font references were being dynamically constructed so that they could be lazily loaded. Is that right? Webpack I think essentially does that for you, so maybe that's where this friction is coming up.

**Comment by pkra** [comment]
> it is trying to get a bunch of font files which it can't find.

I had added a note on this at https://github.com/mathjax/mj3-demos/issues/3 (the copy-webpack plugin helps), I guess I should've posted it here.

> It seems that the font paths are hardcode

Yes but https://github.com/mathjax/mathjax-v3/pull/67 will allow you to configure the URL (should be in the next alpha release).

>  I got the impression that the font references were being dynamically constructed so that they could be lazily loaded. Is that right?

Yes insofar as the stylesheet is generate on the fly (so webpack won't pick up on it). Given the size of the stylesheet, it doesn't make much sense to have it separate.

**Comment by jasongrout** [comment]
> I had added a note on this at mathjax/mj3-demos#3 (the copy-webpack plugin helps), I guess I should've posted it here.

Thanks - I saw that but couldn't remember where. That's copying those files to where they will be looked for in the demo. In our case (as a JupyterLab plugin), we don't get to modify the webpack config (as the plugin system now stands). It would be great if there was a way for webpack to understand where those files were.

> Yes but #67 will allow you to configure the URL (should be in the next alpha release).

That helps, but still doesn't enable webpack to automatically find the fonts and package them up.

> Given the size of the stylesheet, it doesn't make much sense to have it separate.

I'm curious about this - are you saying it is too large or too small?

Are you lazily loading the fonts because you are optimizing for loading time, or because the things you are loading are not known at compile time, or for some other reason? If the former, maybe we can do things in a more webpack-friendly manner. If the latter, then of course webpack won't know either, so we'll have to figure out something else.

**Comment by pkra** [comment]
> In our case (as a JupyterLab plugin), we don't get to modify the webpack config (as the plugin system now stands). 

Right. We need to work out something that helps in such a case.

> It would be great if there was a way for webpack to understand where those files were.

For the time being, maybe try a custom stylesheet specifying just the `font-face` rules?

> That helps, but still doesn't enable webpack to automatically find the fonts and package them up.

If not all fonts need to be local, then a CDN copy could do the trick temporarily?

> I'm curious about this - are you saying it is too large or too small?

Too large.

> Are you lazily loading the fonts because you are optimizing for loading time, or because the things you are loading are not known at compile time, or for some other reason?

I don't think lazy loading of fonts specifically has been considered much. (Our performance issues used to overshadow such details.) The stylesheet is generated and injected at render time; I suspect the main reason is that MathJax has simply always done that.

The stylesheet could be generated server-side (and in static content, could be optimized to only include rules needed for the given content but that won't help your use case I suspect). 

However, the stylesheet is quite large as a lot of rendering logic has moved into CSS rules. We've already discussed potential shifts in the approach if that turns out to be too problematic.

Of course, browsers should only load the fonts when they're used and you can preload the fonts yourself should you want to (again, a partial, custom stylesheet should do the trick).

**Comment by jasongrout** [comment]
Davide discussed this in the Technical Advisory committee meeting. What we decided was (feel free to correct me!):

1. use a custom output jax class that generates the fontface css file, which you then capture and save to a css file. This is done once, before anything is running. Put this css file on the page however you want (for example, by including it directly with a style tag).
2. Subclass the output jax to not insert the fontface URLs on the page dynamically, and pass that new output jax into the system somehow.

@dpvc said he'd work on a short example illustrating this.

**Comment by pkra** [comment]
Just to add: this will be based on the new 3.0.0-alpha.2 (which is out).

**Comment by dpvc** [comment]
The examples are in the `limited-css` branch (based off the `alpha` branch), and are discussed in the [developer's forum](https://groups.google.com/d/msg/mathjax-dev/CBCSCHSpML8/XG7I6BFPBgAJ).

**Comment by jasongrout** [comment]
Thanks! I've added a note to https://github.com/jupyterlab/jupyter-renderers/pull/69 indicating we can move forward again.

**Comment by dpvc** [comment]
The `fontURL` option is in the 3.0.0 release, so I'm closing this.
