### ISSUE TITLE
Requesting to add mathjax in github markdown

### ISSUE THREAD

**Issue by Talha76** [mathjax/MathJax-src#813]
Does github now support markdown with mathjax? If it doesn't please add this feature. If it does give me some resources please.

**Comment by pkra** [comment]
You are in the wrong place. You want to support one of the items listed under https://github.com/github/feedback/discussions?discussions_q=mathjax

**Comment by pkra** [comment]
Well, that was quick: https://github.blog/2022-05-19-math-support-in-markdown/
