### ISSUE TITLE
"ReferenceError: window is not defined" when dev page reloaded.

### ISSUE THREAD

**Issue by MartinLBarranco** [mathjax/MathJax-src#840]
When I refresh the page, window variable from node_modules/mathjax-full/js/adaptors/browserAdaptor.js:6:45 seems to not exists anymore. Therefore the page doesn't work anymore.

Ask for more info if you need it.

**Comment by dpvc** [comment]
There is not enough information to diagnose your issue, and you have posted it to the wrong repository.  Please use the [MathJax issue tracker](https://github.com/mathjax/MathJax/issues) if you are having an issue (this issue tracker is only for structural issues of the source repository).

You will need to look carefully at the issue trample and fill out as much of that as you can.  For example, it seems that you are not using MathJax components, but are loading MathJax modules by hand, so you will need to be clear about how you are doing that, and how you re packaging your application (e.g., using webpack or some other similar program).  A a link to a minimal example page would be particularly helpful.

I'm closing this issue.  Open a new one at the link above if you can provide the needed details.
