### ISSUE TITLE
Reverse process

### ISSUE THREAD

**Issue by artyaaaa** [mathjax/MathJax-src#882]
Is it possible to somehow use your service to turn a mathematical problem (for example, with integrals) from a pdf file into a text that will be perceived by the common text editor

**Comment by zorkow** [comment]
That is not really MathJax's use case. Also extracting formulas correctly from PDFs is a highly non-trivial problem (cf. https://link.springer.com/chapter/10.1007/978-3-642-31374-5_29)
We used to maintain a system called MaxTract, which is unfortunately now defunct. 
There is a new one being developed by the Assistech group at IIT Delhi called RAVI, but it is not yet publicly available. I can alert you once something is released.

For now there are only commercial solutions that I can think of that might help: The Infty system (they reimplemented some of the Maxtract techniques) or maybe using OCR via MathPix.
