### ISSUE TITLE
use mathjax3 in andriod5 show error  "getExplicit of null"

### ISSUE THREAD

**Issue by Daisy1213** [mathjax/MathJax-src#918]
Please submit MathJax bug reports to

https://github.com/mathjax/MathJax/issues

unless they are about structural issues in this repository (e.g., the package.json file, the compilation process, the repository layout, etc).  Bugs with how MathJax works should be reported at the link above.

If you are not part of the MathJax team, it is unlikely that you should be posting an issue here.  Use the tracker linked above instead.

**Comment by dpvc** [comment]
As mentioned in the template for the issue tracker (as you can see above), your issue should be reported to the issue tracker in the MathJax repository, not MathJax-src.  When you make your report there, please follow the instructions in the issue template.  Note than an issue title does not constitute sufficient information to diagnose and respond to your issue.
