### ISSUE TITLE
ts/util/asyncLoad/node.js needs ESM version

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#979]
On develop:

https://github.com/mathjax/MathJax-src/blob/49db078a876cce1f2157c9c58fb98bb145a09068/ts/util/asyncLoad/node.ts#L32-L36

both `__dirname` and the check&use of `require` were causing me trouble when using ES modules.

The following seemed to work for me (though I have not yet tested it thoroughly):

```js
import { fileURLToPath } from 'url'
import * as path from 'path';

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const root = path.dirname(path.dirname(__dirname));
mathjax.asyncLoad = async (name) => {
    return await import((name.charAt(0) === '.' ? path.resolve(root, name) : name)+'.js');
};
```

Especially the `+'.js'` part seems "wrong" but perhaps this is useful to others.

**Comment by dpvc** [comment]
The [`esm.ts`](https://github.com/mathjax/MathJax-src/blob/49db078a876cce1f2157c9c58fb98bb145a09068/ts/util/asyncLoad/esm.ts) file is the one for use with ES modules.  `node.js` is for cjs modules.   Since these are not imported by MathJax itself, I though users could select the right one themselves, but I forgot to document it (there was a *lot* to include in the ESM notes).

It would be possible to make ,js and cjs versions of this file and use the `exports` object in `packages.json` to select like some of the other ones, but I didn't think it was necessary.  But I should have documented the `esm.js` file.

**Comment by pkra** [comment]
Ah, I didn't see esm.js on the develop branch. Thank you for clarifying!

**Comment by pkra** [comment]
FWIW esm.js fails for me. It looks like it's resolving the path relative to the folder containing the module it's imported into (instead of the base folder where node_modules lives). It also seems to fail to add `.js` to the path.

**Comment by dpvc** [comment]
Is this a webpacked version?  I have found that webpack doesn't handle the `import.meta.url` as I would have hoped (it replaces it with the source path of the file at webpack time, which is not helpful.  I haven't found a reasonable work-around that does what is needed in webpack.

**Comment by dpvc** [comment]
Also, it turns out `asyncLoad` is used in only two places, and one adds the `.js` while the other does not.  I will need to fix it so they both add the `.js` and you don't add it here.

**Comment by dpvc** [comment]
Also, you could call the `setBaseURL()` function from `esm.js` in order to set the root to the needed location if it is not finding it correctly, at least as a work-around for now.

**Comment by pkra** [comment]
Thanks, Davide. I'm currently using just `mathjax.asyncLoad = async (name) => import(name+'.js')` which appears to work fine in my setting.

**Comment by dpvc** [comment]
It would still help me to know if the failure of `esm.js was in a webpacked version or not, if you are willing to share that.

**Comment by pkra** [comment]
> It would still help me to know if the failure of `esm.js was in a webpacked version or not, if you are willing to share that.

Sorry for missing the question. No, it wasn't in a webpacked version.

**Comment by pkra** [comment]
I was running into this again during an experiment the other day. Even defining `mathjax.asyncload` didn't work in that particular case. 

I noticed that `root ` is defined outside the guarded expression:

https://github.com/mathjax/MathJax-src/blob/8565f9da973238e4c9571a86a4bcb281b1d98d9b/ts/util/asyncLoad/node.ts#L30-L36

I didn't have a lot of time so I just moved the line in my installation - after which my defined mathjax.asyncload worked.

I thought I'd leave a not here in case it's interesting / anyone else runs into this. 

Hopefully the typescript/esm/webpack situation eventually improves enough for MathJax to find a universal solution. (The new `import.meta.dirname` seems promising.)

**Comment by dpvc** [comment]
@pkra, remember that `ts/util/asyncLoad/esm.js` is the one to use for when you are using ESM modules (`node.js` is for CommonJS usage).  While writing tests for the ts/util directory the other day, I found that there were some inconsistencies among the various `ts/util/asyncLoad` implementations.  I have submitted a PR that fixes those (along with adding the tests), but you could grab the `esm.js` file from [that PR](https://github.com/mathjax/MathJax-src/pull/1105/files#diff-fa3998814d9c72a0a1d4d34209006a2fd994d9ade8f8b5ba2657bf1a78bdc31b) if you want.

**Comment by pkra** [comment]
@dpvc interesting I had forgotten about this. However, `node_modules/mathjax-full/mjs/util/asyncLoad/node.js` is what's being loaded for me, without me taking any action to load it (and while specifying mathjax.asyncload myself).

**Comment by pkra** [comment]
Sorry, I have to correct myself. I found where node.js was still being loaded.

Sigh. I'm very good at only producing noise these days - my apologies once again.

**Comment by pkra** [comment]
Re-adjusting, I'm running into other errors. But that's for another time.
